version: '3.8'

services:

  prod-db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: IAS
      POSTGRES_USER: iasadmin
      POSTGRES_PASSWORD: iaspassword
    volumes:
      - postgresql-prod-data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - prod-db
    environment:
      IAS_SETTINGS_DATABASES: '{"default":{"HOST":"prod-db","PORT":"5432"}}'
      IAS_SETTINGS_IN_DOCKER: 'true' # Boolean values should be passed as strings
      IAS_SETTINGS_SECRET_KEY: 'hsj%0i%y$0axu_n0f%+#j(7r)cy85la8c0inzpx!wv)=m&!6*f)j' # String value
      IAS_SETTINGS_CAMERA_IP: '' # Empty string
      IAS_SETTINGS_DEBUG: 'false' # Boolean values should be passed as strings

volumes:
  postgresql-prod-data:
    driver: local
