version: '3.8'

services:

  prod-db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql-prod-data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - prod-db
    environment:
      IAS_SETTINGS_DATABASES: '{"default":{"HOST":"prod-db","PORT":"5432"}}' # JSON string
      IAS_SETTINGS_IN_DOCKER: ${IAS_SETTINGS_IN_DOCKER} # Boolean values should be passed as strings
      IAS_SETTINGS_SECRET_KEY: ${IAS_SETTINGS_SECRET_KEY} # String value
      IAS_SETTINGS_CAMERA_IP: ${IAS_SETTINGS_CAMERA_IP} # Empty string
      IAS_SETTINGS_DEBUG: ${IAS_SETTINGS_DEBUG} # Boolean values should be passed as strings

volumes:
  postgresql-prod-data:
    driver: local
