# Generated by Django 4.2 on 2025-03-31 16:51

from django.db import migrations, models
import ias.core_apps.staffs.models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_image',
            field=models.ImageField(blank=True, default='/profile_images/default_profile.png', upload_to=ias.core_apps.staffs.models.staff_directory_path),
        ),
    ]
